Repository NCATComp410/comp410_summer2020, pull requests merged in 2020-07, with the labels that each got.

#45 Pecan Cookies Sprint One Issue #14
  demo.py
  dfstools/__init__.py
  dfstools/src/data_tools.py
  dfstools/src/relationship_tools.py
  dfstools/tests/sprint_one_log.txt
  dfstools/tests/test_relationship_tools.py
  peacn_cookies_sprint_one.py
  test.txt
Labels: PecanCookies, help wanted

#47 Issue 46
  dfstools/src/relationship_tools.py
  dfstools/tests/logs/sprint_one_log.txt
  dfstools/tests/logs/sprint_one_log2.txt
Labels: PecanCookies, help wanted

#56 Finished parent_child_relationship function (TeamBeast)
  dfstools/src/relationship_tools.py
Labels: TeamBeast

#62 implement find_primary_key_candidates()
  dfstools/src/data_tools.py
Labels: CrestCoders

#64 Fixes #55, Fixes #59
  dfstools/src/relationship_tools.py
  peacn_cookies_sprint_one.py
Labels: PecanCookies
